# Netlify Build Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - explicitly set NODE_ENV for install and build steps
  command = "npm install && npm run build"
  
  # Directory to publish (relative to root of repository)
  publish = "_site"
  
  # Node.js version and NPM flags (keeping NPM_FLAGS as a fallback, though NODE_ENV trick should work)
  environment = { NODE_VERSION = "18", NODE_ENV = "production" }

# Production context
# NODE_ENV is already set to production here by default, and for the build step by the command above
[context.production]
  # This is effectively covered by the main [build.environment]
  # environment = { NODE_ENV = "production" }

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets
    Cache-Control = '''
    public,
    max-age=604800,
    must-revalidate'''

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache assets for 1 year
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

# Redirects (example - uncomment and modify as needed)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301

# Plugins (optional)
[[plugins]]
  # Automatically generate a sitemap
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "_site"
    exclude = [
      "./404.html"
    ] 